"""auto generation of adding phone number col to users table

Revision ID: 3241e4bc6e3c
Revises: f2c845fa4ce9
Create Date: 2025-07-14 18:05:56.503126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3241e4bc6e3c'
down_revision = 'f2c845fa4ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
