name: Build and Deploy Code

#what trigger this code to run: push/pull
# can specify on which branch to run 
#on: [push, pull_request] # allows to run on both
on: [push, pull_request]

env: 
  DATABASE_HOSTNAME=localhost

#once we define the triggers above, we define jobs
jobs:
  job1: #specify on what OS it runs on
    env:
      DATABASE_HOSTNAME=localhost
      DATABASE_PORT=5432
      DATABASE_PASSWORD=123
      DATABASE_NAME=apicourse
      DATABASE_USERNAME=postgres
      SECRET_KEY="f583ace4e10f68e78cb6c28e2b7a6ac553c2ce768f7b38da999d68b06320c425"
      ALGORITHM="HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES=30
    runs-on: ubuntu-latest
    #list of steps
    steps:
    #name: human readable description of step
      - name: pulling git repo # since we pull out our repo, we have access to all the repository code
        #uses: actual command to run on our VM to pull git repo -> find on GH marketplace
        uses: actions/checkout@v2 # special action that we get from GH marketplace
      - name: say hi to Julia
        run: echo "Hello Julia, I am gonna fuck you hard"
      - name: Install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      #we want to upgrade pip
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies 
        run: pip install -r requirements.txt
      - name: test with pytest
        run: | # | means that a list of commands follow
          pip install pytest
          pytest

      
      



